# -*- coding: utf-8 -*-
"""
eSIM competitor promo/discount codes — structured dataset builder.

Emits (into _competitors/promos/):
  <brand>.json      one file per brand: offers[] + referral + loyalty + notes
  promos_all.csv    flat table, one row per offer
  promos.json       all brands in one object

Schema per offer:
  code         str|""        coupon/promo code ("" for pure referral/loyalty, no typed code)
  kind         str           coupon | referral | loyalty | card_benefit | student | free_trial | bonus_data | cashback
  discount     str           human headline, e.g. "15% off", "$5 off", "+6 GB", "€2/day"
  percent      float|None    numeric % when it is a straight percentage
  amount       float|None    fixed amount when not a percentage
  currency     str|""        currency of `amount`
  audience     str           new | existing | all | students | cardholders | invited_friend
  where        str           web+app | app | web
  min_spend    str|""        minimum spend if any
  max_discount str|""        cap if any
  stackable    str           no | yes | one_per_order | unknown
  uses         str           once_per_account | unlimited | unknown | ...
  scope        str           what it applies to (all plans, unlimited only, ...)
  expires      str|""        date or "ongoing"/"unknown"
  terms        list[str]     extra rule lines
  source       str           official | aggregator
  source_url   str
  verified     str           date string or ""
  confidence   str           official | verified-thirdparty | reported
"""

import json, csv, os

BASE = r"D:\HUGO test\29.1_windows-amd64\hugo_0.159.1_windows-amd64\esimsift-main\esimsift-main\_competitors"
OUT = os.path.join(BASE, "promos")
CAPTURED = "2026-10-04"

O = lambda **k: {**{f: None for f in (
    "code", "kind", "discount", "percent", "amount", "currency", "audience",
    "where", "min_spend", "max_discount", "stackable", "uses", "scope",
    "expires", "terms", "source", "source_url", "verified", "confidence")}, **k}

BRANDS = {}

# ---------------------------------------------------------------- Airalo
BRANDS["airalo"] = {
    "brand_key": "airalo",
    "brand_name": "Airalo",
    "brand_alias": ["airalo.com"],
    "official_site": "https://www.airalo.com/",
    "captured": CAPTURED,
    "offers": [
        O(code="NEWTOAIRALO15", kind="coupon", discount="15% off", percent=15.0,
          currency="USD", audience="new", where="web+app",
          max_discount="100 USD", stackable="no", uses="once_per_account",
          scope="any eSIM (local / regional / global / unlimited), 200+ destinations",
          expires="2026-12-31",
          terms=["One redemption per customer",
                 "Cannot be combined with other promotions or with Airmoney credit",
                 "Payment by card / PayPal / Apple Pay / Google Pay only",
                 "Campaign ends early if the redemption cap is reached"],
          source="aggregator", source_url="https://localsinsider.com/digital-life/esims/airalo-esim-review/",
          verified="2026-10", confidence="verified-thirdparty"),
        O(code="AIRALOESIM10", kind="coupon", discount="10% off", percent=10.0,
          currency="USD", audience="existing", where="web+app",
          min_spend="10 USD", stackable="no", uses="once_per_account",
          scope="any eSIM priced 10 USD or more", expires="2026-12-31",
          terms=["Returning customers", "Same checkout field (Apply code / Use Airmoney)"],
          source="aggregator", source_url="https://localsinsider.com/digital-life/esims/airalo-esim-review/",
          verified="2026-10", confidence="verified-thirdparty"),
        O(code="VIP15", kind="coupon", discount="15% off (new users)", percent=15.0,
          currency="", audience="new", where="web+app", min_spend="none",
          scope="all plans (single-country / regional / global)", expires="ongoing",
          source="aggregator", source_url="https://xincoupon.com/?p=44109/",
          verified="2026-10", confidence="reported"),
        O(code="VIP10", kind="coupon", discount="10% off (returning)", percent=10.0,
          currency="", audience="existing", where="web+app", min_spend="none",
          scope="all plans", expires="ongoing",
          source="aggregator", source_url="https://xincoupon.com/?p=44109/",
          verified="2026-10", confidence="reported"),
        O(code="ESIMADVICE15", kind="coupon", discount="15% off", percent=15.0,
          currency="", audience="all", where="web+app", scope="all plans",
          expires="unknown",
          source="aggregator", source_url="https://esimtweaks.com/airalo-vs-saily",
          verified="2026-09", confidence="reported"),
        O(code="ESIMP15", kind="coupon", discount="15% off", percent=15.0,
          currency="", audience="all", where="web+app", scope="all plans",
          expires="unknown",
          source="aggregator", source_url="https://www.esimdeals.io/esim/turkey/deals",
          verified="2026-09", confidence="reported"),
        O(code="", kind="referral", discount="Give $3, get $3 (Airmoney credit)",
          amount=3.0, currency="USD", audience="all", where="web+app",
          stackable="no", scope="referral credit on first purchase of friend",
          expires="ongoing",
          terms=["Not combinable with a promo code — use on small orders",
                 "On orders above ~20 USD the 15% code saves more"],
          source="official", source_url="https://www.airalo.com/",
          verified="2026-10", confidence="official"),
        O(code="", kind="card_benefit", discount="15% off (Consumer Cellular partnership)",
          percent=15.0, currency="", audience="cardholders", where="web",
          scope="any eSIM via the co-branded Consumer Cellular portal",
          expires="2026-10-31",
          terms=["New and existing Airalo + Consumer Cellular customers",
                 "Auto-applied via portal, or use the designated promotional code"],
          source="official",
          source_url="https://www.airalo.com/de/about-us/press-releases/airalo-consumer-cellular",
          verified="2026-08-18", confidence="official"),
    ],
    "notes": ["Airalo is proxy-blocked from this environment (requests + Playwright both timed out); data collected via aggregators/official press."],
}

# ---------------------------------------------------------------- Holafly
BRANDS["holafly"] = {
    "brand_key": "holafly",
    "brand_name": "Holafly",
    "brand_alias": [],
    "official_site": "https://esim.holafly.com/",
    "captured": CAPTURED,
    "offers": [
        O(code="MYESIMNOW5", kind="coupon", discount="5% off", percent=5.0,
          currency="", audience="all", where="web+app", scope="all eSIM plans",
          expires="ongoing",
          terms=["Code published on Holafly's own blog content pages"],
          source="official", source_url="https://esim.holafly.com/internet/best-unlimited-data-plans/",
          verified=CAPTURED, confidence="official"),
        O(code="B2BVIP5", kind="coupon", discount="5% off (whole site)", percent=5.0,
          currency="", audience="all", where="web+app", scope="all plans",
          expires="ongoing",
          source="aggregator", source_url="https://xincoupon.com/?p=44109/",
          verified="2026-10", confidence="reported"),
        O(code="THEDUFRESNES", kind="coupon",
          discount="5% off eSIMs · 10% off Plans · up to 20% quarterly · up to 30% annual",
          percent=5.0, currency="", audience="all", where="web+app",
          scope="destination eSIMs (5%) and Holafly Plans subscriptions (10%+)",
          expires="ongoing",
          terms=["Ambassador code", "Verified September 2026"],
          source="aggregator",
          source_url="https://thedufresnestravel.com/pages/holafly-esim-what-to-know-before-you-buy-buyers-guide",
          verified="2026-09", confidence="verified-thirdparty"),
        O(code="TRAVELESIMEXPERT", kind="coupon",
          discount="5% off eSIMs · 10% off Global Plans", percent=5.0,
          currency="", audience="all", where="web+app",
          scope="all plans incl. monthly", expires="ongoing",
          terms=["Last verified 2026-09-14 by the publisher"], 
          source="aggregator", source_url="https://travelesimexpert.com/holafly-discount-code",
          verified="2026-09-14", confidence="verified-thirdparty"),
        O(code="ADAMANDLINDS", kind="coupon",
          discount="5% off eSIMs · 10% off Plans", percent=5.0,
          currency="", audience="all", where="web+app",
          scope="destination/regional eSIMs 5%, Plans 10%", expires="ongoing",
          terms=["Not limited to first orders", "Annual billing + code ≈ 23.5% total off"],
          source="aggregator",
          source_url="https://adamandlinds.com/blog/best-holafly-deals-november-2025-promo-code-discount/",
          verified="2026-09-04", confidence="verified-thirdparty"),
        O(code="THEPROFESSIONALHOBO", kind="coupon", discount="5% off eSIMs · 10% off Plans",
          percent=5.0, currency="", audience="all", where="web+app",
          scope="regular eSIMs 5%, Plans 10% for 12 months", expires="ongoing",
          source="aggregator",
          source_url="https://www.theprofessionalhobo.com/finding-the-best-esim-for-international-travel-your-ultimate-guide",
          verified="2026", confidence="reported"),
        O(code="GOINGAWESOMEPLACES", kind="coupon", discount="5% off", percent=5.0,
          currency="", audience="all", where="web+app", scope="all eSIM plans",
          expires="ongoing",
          source="aggregator", source_url="https://goingawesomeplaces.com/best-esims-for-usa-travel/",
          verified="2026", confidence="reported"),
        O(code="", kind="referral", discount="Race to Rewards — invite friends, earn up to €100",
          amount=100.0, currency="EUR", audience="all", where="app",
          scope="referral rewards", expires="ongoing",
          source="official", source_url="https://esim.holafly.com/",
          verified=CAPTURED, confidence="official"),
    ],
    "notes": ["No standing 20%/30% coupon exists — above 5% on eSIMs only during Holafly's own seasonal sales (e.g. Black Friday).",
              "Annual Plans billing takes ~15% off first, then the code adds ~10%.",
              "Homepage banner 'Race to Rewards' = referral programme (official)."],
}

# ---------------------------------------------------------------- Nomad
BRANDS["nomad"] = {
    "brand_key": "nomad",
    "brand_name": "Nomad eSIM",
    "brand_alias": ["nomadesim.com"],
    "official_site": "https://www.nomadesim.com/",
    "captured": CAPTURED,
    "offers": [
        O(code="BEYOND20", kind="coupon", discount="20% off", percent=20.0,
          currency="", audience="all", where="web+app", scope="autumn campaign — selected plans",
          expires="unknown (seasonal 'Beyond the Usual' campaign)",
          terms=["Rendered in the site's own promo banner"],
          source="official", source_url="https://www.nomadesim.com/",
          verified=CAPTURED, confidence="official"),
        O(code="FALL30", kind="coupon", discount="30% off 2+ eSIMs", percent=30.0,
          currency="", audience="all", where="web+app",
          min_spend="2 or more eSIMs in one order", scope="multi-eSIM orders",
          expires="unknown (autumn campaign)",
          source="official", source_url="https://www.nomadesim.com/",
          verified=CAPTURED, confidence="official"),
        O(code="RUNAWAY20", kind="coupon", discount="20% off", percent=20.0,
          currency="", audience="all", where="web+app", scope="most plans",
          expires="ongoing",
          terms=["Excludes add-on data, business-travel plans, unlimited plans, plans already on sale, the Thailand 50GB plan, and plans under 5 USD"],
          source="aggregator", source_url="https://runawaytraveller.com/nomad-esim-review",
          verified="2026", confidence="reported"),
        O(code="ESIMDNOMAD20", kind="coupon", discount="20% off", percent=20.0,
          currency="", audience="all", where="web+app", scope="eligible plans",
          expires="unknown",
          terms=["Partner code", "Verified 2026-09-29 by the publisher"],
          source="aggregator", source_url="https://www.esimdeals.io/providers/nomad",
          verified="2026-09-29", confidence="verified-thirdparty"),
        O(code="LOCALS", kind="coupon", discount="15% off first purchase", percent=15.0,
          currency="", audience="new", where="web+app", scope="first purchase",
          expires="ongoing",
          source="aggregator",
          source_url="https://localsinsider.com/digital-life/esims/the-best-global-esims-for-international-travel/",
          verified="2026", confidence="reported"),
        O(code="", kind="referral", discount="$5 off for you and up to 5 friends", amount=5.0,
          currency="USD", audience="invited_friend", where="app",
          min_spend="plans priced 5 USD or more", scope="referral",
          expires="ongoing",
          terms=["You receive $5 for every successful referral"],
          source="official", source_url="https://www.nomadesim.com/",
          verified=CAPTURED, confidence="official"),
        O(code="", kind="loyalty", discount="15% off add-on plans (Nomad Pass members)",
          percent=15.0, currency="", audience="existing", where="app",
          scope="Nomad Pass: 1GB Europe regional data / month for USD3",
          expires="ongoing",
          terms=["Requires latest app version"],
          source="official", source_url="https://www.nomadesim.com/",
          verified=CAPTURED, confidence="official"),
        O(code="", kind="student", discount="Student discount via Student Beans",
          currency="", audience="students", where="web", scope="student verification platform",
          expires="ongoing",
          source="official", source_url="https://www.nomadesim.com/",
          verified=CAPTURED, confidence="official"),
        O(code="", kind="free_trial", discount="Free 1GB trial eSIM", amount=None,
          currency="", audience="new", where="app",
          scope="free 1GB for the next trip (76 destinations per one source)",
          expires="ongoing", source="official", source_url="https://www.nomadesim.com/",
          verified=CAPTURED, confidence="official"),
    ],
    "notes": ["Homepage banner set (rendered): BEYOND20 (20%) + FALL30 (30% off 2+ eSIMs).",
              "Nomad Membership / Nomad Pass = loyalty tier by annual spend.",
              "Referral: $5 off for you + up to 5 friends ($5 min spend)."],
}

# ---------------------------------------------------------------- Jetpac
BRANDS["jetpac"] = {
    "brand_key": "jetpac",
    "brand_name": "Jetpac Travel eSIM",
    "brand_alias": ["jetpacglobal.com"],
    "official_site": "https://www.jetpacglobal.com/",
    "captured": CAPTURED,
    "offers": [
        O(code="ESIM15", kind="coupon", discount="15% off", percent=15.0,
          currency="", audience="all", where="web+app", scope="eSIM plans",
          expires="unknown",
          terms=["Found embedded in the site's own JSON payload"],
          source="official", source_url="https://www.jetpacglobal.com/",
          verified=CAPTURED, confidence="official"),
        O(code="Teresa20", kind="coupon", discount="20% off", percent=20.0,
          currency="", audience="all", where="web+app", scope="eSIM plans",
          expires="unknown",
          terms=["Found embedded in the site's own JSON payload (partner/ambassador code)"],
          source="official", source_url="https://www.jetpacglobal.com/",
          verified=CAPTURED, confidence="official"),
        O(code="", kind="coupon", discount="Extra 10% off", percent=10.0,
          currency="", audience="all", where="web", scope="promotional banner",
          expires="unknown",
          terms=["Site promo copy: 'Buy your Jetpac eSIM today and get extra 10% off'"],
          source="official", source_url="https://www.jetpacglobal.com/",
          verified=CAPTURED, confidence="official"),
        O(code="FYESIM15", kind="coupon", discount="15% off first purchase", percent=15.0,
          currency="", audience="new", where="web+app", scope="first purchase",
          expires="ongoing", terms=["Once per customer"],
          source="aggregator", source_url="https://findyouresim.co.uk/discount-codes",
          verified="2026-09", confidence="reported"),
        O(code="", kind="referral", discount="Refer a friend", currency="",
          audience="all", where="app", scope="referral programme",
          expires="ongoing", source="official",
          source_url="https://www.jetpacglobal.com/referral",
          verified=CAPTURED, confidence="official"),
        O(code="", kind="bonus_data", discount="LoungeKey™ airport-lounge voucher on qualifying flight delay",
          currency="", audience="all", where="web",
          scope="flight-delay compensation perk (via FlightStats)",
          expires="ongoing", source="official", source_url="https://www.jetpacglobal.com/",
          verified=CAPTURED, confidence="official"),
    ],
    "notes": ["Jetpac's own JSON payload (window.__NEXT_DATA__-style) contains ESIM15 and Teresa20."],
}

# ---------------------------------------------------------------- GigSky
BRANDS["gigsky"] = {
    "brand_key": "gigsky",
    "brand_name": "GigSky",
    "brand_alias": ["gigsky.com"],
    "official_site": "https://www.gigsky.com/",
    "captured": CAPTURED,
    "offers": [
        O(code="", kind="card_benefit", discount="Up to 30% off all GigSky plans",
          percent=30.0, currency="", audience="cardholders", where="app",
          scope="eligible Visa cardholders — every plan (175+ countries; programmes split by issuing region: Visa USA / Canada / LATAM+Caribbean+Brazil / Japan / Argentina / Hong Kong & Macau)",
          expires="ongoing",
          terms=["'Evergreen discounts' — Visa Travel Benefits",
                 "Also unlocks complimentary global data (up to 7 days unlimited) in 175+ countries",
                 "Available to eligible cardholders everywhere",
                 "Enter your Visa card number in the GigSky app to check entitlements",
                 "You can add multiple cards; redeem each benefit separately",
                 "'All plans up to 30% off' per the official Visa Benefits page"],
          source="official", source_url="https://www.gigsky.com/visa-benefits",
          verified=CAPTURED, confidence="official"),
        O(code="", kind="referral", discount="Give 25% off, get 25% off (Share & Save)",
          percent=25.0, currency="", audience="invited_friend", where="app",
          scope="referral programme", expires="ongoing",
          source="official", source_url="https://www.gigsky.com/refer",
          verified=CAPTURED, confidence="official"),
        O(code="", kind="loyalty", discount="5% credit back on every purchase (Rewards)",
          percent=5.0, currency="", audience="existing", where="app",
          scope="loyalty credits", expires="ongoing",
          source="aggregator",
          source_url="https://www.theprofessionalhobo.com/finding-the-best-esim-for-international-travel-your-ultimate-guide",
          verified="2026", confidence="reported"),
        O(code="", kind="referral", discount="$3 per successful referral", amount=3.0,
          currency="USD", audience="existing", where="app",
          scope="Refer-a-Friend", expires="ongoing",
          source="aggregator",
          source_url="https://www.theprofessionalhobo.com/finding-the-best-esim-for-international-travel-your-ultimate-guide",
          verified="2026", confidence="reported"),
        O(code="", kind="free_trial", discount="Free 100MB trial (7 days, no card required)",
          currency="", audience="new", where="app", scope="trial eSIM",
          expires="ongoing", source="official", source_url="https://www.gigsky.com/free-trial",
          verified=CAPTURED, confidence="official"),
        O(code="", kind="bonus_data", discount="50% off GigSky One (25GB/month subscription)",
          percent=50.0, currency="", audience="all", where="app",
          scope="GigSky One subscription launch special", expires="unknown (2026 update)",
          source="aggregator",
          source_url="https://www.theprofessionalhobo.com/finding-the-best-esim-for-international-travel-your-ultimate-guide",
          verified="2026", confidence="reported"),
        O(code="ESIMADVICE15", kind="coupon", discount="15% off", percent=15.0,
          currency="", audience="all", where="web+app", scope="eligible eSIM products",
          expires="unknown", source="aggregator", source_url="https://esim.qpon/?p=234",
          verified="2026-08-25", confidence="reported"),
        O(code="ESIMD", kind="coupon", discount="15% off", percent=15.0,
          currency="", audience="all", where="web+app", scope="eligible plans",
          expires="unknown", terms=["eSIM Deals partner code"],
          source="aggregator", source_url="https://www.esimdeals.io/esim/turkey/deals",
          verified="2026-09", confidence="verified-thirdparty"),
        O(code="REWARDS15", kind="coupon", discount="15% off eligible eSIM purchases",
          percent=15.0, currency="", audience="all", where="web+app",
          scope="eligible products", expires="2026 (Rewards Canada 25th-anniversary promo)",
          source="aggregator", source_url="http://rewardscanada.ca/25",
          verified="2026", confidence="reported"),
        O(code="GOINGAWESOME", kind="coupon", discount="20% off all eSIM orders",
          percent=20.0, currency="", audience="all", where="web+app",
          scope="all eSIM orders", expires="ongoing",
          source="aggregator", source_url="https://goingawesomeplaces.com/best-esims-for-usa-travel/",
          verified="2026", confidence="reported"),
        O(code="Freaking15", kind="coupon", discount="15% off all eSIMs (land + inflight)",
          percent=15.0, currency="", audience="all", where="web+app",
          scope="all GigSky eSIMs", expires="ongoing",
          source="aggregator",
          source_url="https://freakingnomads.com/best-esim-providers/",
          verified="2026", confidence="reported"),
        O(code="TANG149", kind="coupon", discount="$3 credit on sign-up", amount=3.0,
          currency="USD", audience="new", where="app", scope="sign-up",
          expires="ongoing",
          source="aggregator", source_url="https://goingawesomeplaces.com/best-esims-for-usa-travel/",
          verified="2026", confidence="reported"),
        O(code="AFFMAVEN10", kind="coupon", discount="10% off (repeat orders)", percent=10.0,
          currency="", audience="existing", where="web+app", scope="repeat orders",
          expires="unknown", source="aggregator", source_url="https://esim.qpon/?p=234",
          verified="2026-08-25", confidence="reported"),
    ],
    "notes": ["GigSky publishes a Visa cardholder benefit page (up to 30% off) — the strongest standing discount found.",
              "Visa programme is split by card-issuing region (USA, Canada, LATAM/Caribbean/Brazil, Japan, Argentina, Hong Kong & Macau) with region-specific entitlements.",
              "Official pages: /visa-benefits, /refer (Share & Save 25/25), /free-trial. NOTE: /promotions and /refer are SPAs that render 'Oops! Something went wrong' when fetched directly — terms come from flight JSON + the Visa page."],
}

# ---------------------------------------------------------------- Quibity
BRANDS["quibity"] = {
    "brand_key": "quibity",
    "brand_name": "Quibity eSIM",
    "brand_alias": ["quibity.com"],
    "official_site": "https://quibity.com/",
    "captured": CAPTURED,
    "offers": [
        O(code="QUIBITY8", kind="coupon", discount="8% off any eSIM", percent=8.0,
          currency="", audience="all", where="web+app", min_spend="none",
          stackable="one_per_order", uses="once_per_account",
          scope="any plan incl. regional and global, 190+ countries",
          expires="ongoing (page states 'Valid in October 2026')",
          terms=["One use per customer account, one coupon per order",
                 "Not valid for business and reseller accounts",
                 "Quibity can change or withdraw the code at any time",
                 "Discount taken off before payment"],
          source="official", source_url="https://quibity.com/coupons",
          verified="2026-10", confidence="official"),
        O(code="", kind="loyalty", discount="Exclusive discounts via Travel Journal",
          currency="", audience="existing", where="app",
          scope="unlock exclusive discounts by tracking visited countries",
          expires="ongoing", source="official", source_url="https://quibity.com/",
          verified=CAPTURED, confidence="official"),
        O(code="", kind="loyalty", discount="Usage-based discounts", currency="",
          audience="existing", where="app", scope="pay only for the data you use",
          expires="ongoing", source="official", source_url="https://quibity.com/",
          verified=CAPTURED, confidence="official"),
    ],
    "notes": ["Quibity publishes an official coupons page with a single standing code QUIBITY8 (8%)."],
}

# ---------------------------------------------------------------- BNESIM
BRANDS["bnesim"] = {
    "brand_key": "bnesim",
    "brand_name": "BNESIM",
    "brand_alias": ["bensim", "bnesim.com"],
    "official_site": "https://www.bnesim.com/",
    "captured": CAPTURED,
    "offers": [
        O(code="OCTOBER20", kind="coupon", discount="20% off data plans of 10 GB or more",
          percent=20.0, currency="", audience="all", where="web+app",
          min_spend="plan of 10 GB or more", stackable="unknown",
          uses="once_per_account", scope="data plans >= 10 GB (unlimited + scheduled-activation plans excluded)",
          expires="2026-10-31",
          terms=["Enter OCTOBER20 at checkout",
                 "One use per customer",
                 "Unlimited data plans are NOT included",
                 "Data plans with scheduled activation are NOT included",
                 "BNESIM may modify or cancel the promotion at any time"],
          source="official", source_url="https://www.bnesim.com/offers",
          verified="2026-10-04", confidence="official"),
        O(code="MYBESTSIM", kind="coupon", discount="30% off all plans", percent=30.0,
          currency="", audience="all", where="web+app", min_spend="none",
          scope="all BNESIM eSIM plans", expires="ongoing (no stated expiry)",
          terms=["Exclusive code negotiated by MyBestSim",
                 "Applied at checkout on the official BNESIM store",
                 "Verified by the publisher across Jul–Sep 2026"],
          source="aggregator", source_url="https://mybestsim.com/?p=218373",
          verified="2026-09-04", confidence="verified-thirdparty"),
        O(code="TRAVELESIMEXPERT", kind="coupon", discount="30% off all plans", percent=30.0,
          currency="", audience="all", where="web+app", scope="all plans",
          expires="ongoing",
          terms=["Widely cited as the best standing BNESIM discount"],
          source="aggregator", source_url="https://travelesimexpert.com/best-esim-for-malaysia/",
          verified="2026-10", confidence="verified-thirdparty"),
        O(code="MYBESTSIM20", kind="coupon", discount="20% off all plans", percent=20.0,
          currency="", audience="all", where="web+app", scope="all plans",
          expires="ongoing",
          terms=["Verified on the official store by the publisher"],
          source="aggregator", source_url="https://mybestsim.com/it/fornitore/codice-sconto-bnesim",
          verified="2026-08-20", confidence="verified-thirdparty"),
        O(code="GLOBAL30", kind="coupon", discount="30% off any data plan", percent=30.0,
          currency="", audience="all", where="web+app", scope="any data plan",
          expires="2026-12-13",
          source="aggregator", source_url="https://www.hotdeals.com/coupons/bnesim-promo-codes",
          verified="2026-09", confidence="reported"),
        O(code="WELCOME20", kind="coupon", discount="20% off data plans", percent=20.0,
          currency="", audience="all", where="web+app", scope="data plans",
          expires="2026-12-14",
          source="aggregator", source_url="https://www.hotdeals.com/coupons/bnesim-promo-codes",
          verified="2026-09", confidence="reported"),
        O(code="", kind="cashback", discount="5% cashback in BNE Coins (BNE Wallet)",
          percent=5.0, currency="", audience="existing", where="app",
          scope="every purchase via BNE Wallet", expires="ongoing",
          terms=["BNE Coins never expire"],
          source="official", source_url="https://www.bnesim.com/offers",
          verified=CAPTURED, confidence="official"),
        O(code="", kind="referral", discount="Refer a Friend", currency="",
          audience="all", where="app", scope="referral programme",
          expires="ongoing", source="official", source_url="https://www.bnesim.com/offers",
          verified=CAPTURED, confidence="official"),
        O(code="BX79SA1C", kind="coupon", discount="€3 off first purchase", amount=3.0,
          currency="EUR", audience="new", where="web+app", scope="first purchase",
          expires="2026-12-12",
          source="aggregator", source_url="https://www.hotdeals.com/coupons/bnesim-promo-codes",
          verified="2026-09", confidence="reported"),
        O(code="", kind="bonus_data", discount="+10 GB bonus on the 10 GB/day plan (7-day)",
          currency="", audience="all", where="app", scope="specific plan bonus",
          expires="ongoing", source="aggregator",
          source_url="https://www.bnesim.com/offers", verified=CAPTURED, confidence="reported"),
    ],
    "notes": ["BNESIM = 'bensim'. Official /offers page is a deals hub (JS-rendered) with coupon codes + cashback.",
              "OFFICIAL as of 2026-10-04: OCTOBER20 = 20% off data plans >=10 GB, one use/customer, until 2026-10-31 (unlimited + scheduled-activation plans excluded).",
              "The strongest, most consistently verified third-party code is 30% off (MYBESTSIM / TRAVELESIMEXPERT).",
              "'BNESIMFREE', 'BNESIM50' etc. are flagged as expired/fake by the verifying publisher."],
}

# ---------------------------------------------------------------- Roamless
BRANDS["roamless"] = {
    "brand_key": "roamless",
    "brand_name": "Roamless",
    "brand_alias": ["roamless.com"],
    "official_site": "https://roamless.com/",
    "captured": CAPTURED,
    "offers": [
        O(code="WEB101", kind="coupon", discount="10% off first purchase", percent=10.0,
          currency="", audience="new", where="web+app", scope="first purchase",
          expires="ongoing",
          terms=["Welcome Gift banner rendered on the site itself",
                 "Banner CTA deep-links into the app with the code pre-filled"],
          source="official", source_url="https://roamless.com/",
          verified=CAPTURED, confidence="official"),
        O(code="ROAM25", kind="bonus_data", discount="Free data package (step 1 of promo chain)",
          currency="", audience="new", where="app",
          scope="new account — stack ROAM25 → ROAM50 → ROAM75 in order",
          expires="ongoing",
          terms=["Apply in this exact order immediately after creating a new account"],
          source="aggregator", source_url="https://goingawesomeplaces.com/best-esim-for-japan-travel/",
          verified="2026", confidence="reported"),
        O(code="ROAM50", kind="bonus_data", discount="Free data package (step 2 of promo chain)",
          currency="", audience="new", where="app", scope="new account",
          expires="ongoing",
          source="aggregator", source_url="https://goingawesomeplaces.com/best-esim-for-japan-travel/",
          verified="2026", confidence="reported"),
        O(code="ROAM75", kind="bonus_data", discount="Free data package (step 3 of promo chain)",
          currency="", audience="new", where="app", scope="new account",
          expires="ongoing",
          source="aggregator", source_url="https://goingawesomeplaces.com/best-esim-for-japan-travel/",
          verified="2026", confidence="reported"),
        O(code="ROAM100", kind="bonus_data", discount="+100% extra credits on first purchase",
          currency="", audience="new", where="app", scope="first purchase credit bonus",
          expires="ongoing",
          source="aggregator", source_url="https://goaw.pl/3VJIpih",
          verified="2026", confidence="reported"),
        O(code="AWESOME20", kind="coupon", discount="20% off", percent=20.0,
          currency="", audience="all", where="web+app", scope="all packages",
          expires="ongoing",
          source="aggregator", source_url="https://goingawesomeplaces.com/best-esims-for-usa-travel/",
          verified="2026", confidence="reported"),
        O(code="TMA20", kind="coupon", discount="20% off first purchase", percent=20.0,
          currency="", audience="new", where="web+app", scope="first purchase",
          expires="ongoing",
          source="aggregator", source_url="https://toomanyadapters.com/?p=32246",
          verified="2026-08-31", confidence="reported"),
        O(code="ALCROAM", kind="coupon", discount="25% off first eSIM", percent=25.0,
          currency="", audience="new", where="app", scope="first eSIM (Flex or Fix)",
          expires="ongoing",
          source="aggregator", source_url="https://oman.alcoupon.com/en/discount-codes/roamless",
          verified="2026-09-30", confidence="reported"),
        O(code="ALCRML", kind="coupon", discount="20% off every plan", percent=20.0,
          currency="", audience="existing", where="app", scope="all plans",
          expires="ongoing",
          source="aggregator", source_url="https://oman.alcoupon.com/en/discount-codes/roamless",
          verified="2026-09-30", confidence="reported"),
        O(code="ESIMD", kind="coupon", discount="15% off", percent=15.0,
          currency="", audience="all", where="web+app", scope="eligible plans",
          expires="unknown", terms=["eSIM Deals partner code"],
          source="aggregator", source_url="https://www.esimdeals.io/esim/turkey/deals",
          verified="2026-09", confidence="verified-thirdparty"),
    ],
    "notes": ["Roamless renders a structured promoBanners array in its Next.js payload — WEB101 is the live official code.",
              "Free-tier products exist but are dropped by the site's own price>0 rule.",
              "ROAM25/50/75 is a new-account free-data promo chain, not a % discount."],
}

# ---------------------------------------------------------------- GoMoWorld
BRANDS["gomoworld"] = {
    "brand_key": "gomoworld",
    "brand_name": "GoMoWorld",
    "brand_alias": ["gomoworld.com"],
    "official_site": "https://www.gomoworld.com/en",
    "captured": CAPTURED,
    "offers": [
        O(code="MYBESTSIM", kind="coupon", discount="10% off every eSIM", percent=10.0,
          currency="", audience="all", where="web+app", min_spend="none",
          scope="all GoMoWorld eSIM plans", expires="ongoing (no stated expiry)",
          terms=["Exclusive code negotiated by MyBestSim",
                 "Verified at checkout across Jul–Sep 2026"],
          source="aggregator", source_url="https://mybestsim.com/en/provider/gomoworld-promo-code/",
          verified="2026-09-19", confidence="verified-thirdparty"),
        O(code="TRAVELESIMEXPERT", kind="coupon", discount="10% off all plans", percent=10.0,
          currency="", audience="all", where="web+app", scope="all plans",
          expires="ongoing", source="aggregator",
          source_url="https://travelesimexpert.com/best-esim-for-belgium",
          verified="2026", confidence="verified-thirdparty"),
        O(code="ESIMD", kind="coupon", discount="10% off", percent=10.0,
          currency="", audience="all", where="web+app", scope="eligible plans",
          expires="unknown", terms=["eSIM Deals partner code"],
          source="aggregator", source_url="https://www.esimdeals.io/providers/gomoworld",
          verified="2026-09-24", confidence="verified-thirdparty"),
        O(code="FYESIM", kind="coupon", discount="10% off", percent=10.0,
          currency="", audience="all", where="web+app", scope="eligible plans",
          expires="ongoing",
          source="aggregator", source_url="https://findyouresim.co.uk/providers/gomoworld/bonaire/",
          verified="2026-09-20", confidence="reported"),
        O(code="", kind="bonus_data", discount="+6 GB bonus on selected US plan (US_30GB_30_+6GB)",
          currency="", audience="all", where="app",
          scope="US 30GB 30-day plan -> +6GB bonus", expires="active",
          terms=["Promo object embedded in the site's own offers payload"],
          source="official", source_url="https://www.gomoworld.com/en",
          verified=CAPTURED, confidence="official"),
        O(code="", kind="bonus_data", discount="+4 GB bonus on selected US plan (US_20GB_30_+4GB)",
          currency="", audience="all", where="app",
          scope="US 20GB 30-day plan -> +4GB bonus", expires="active",
          terms=["Promo object embedded in the site's own offers payload"],
          source="official", source_url="https://www.gomoworld.com/en",
          verified=CAPTURED, confidence="official"),
        O(code="", kind="free_trial", discount="1 GB free trial (selected destinations, in-app only)",
          currency="", audience="new", where="app", scope="trial data",
          expires="ongoing", source="official", source_url="https://www.gomoworld.com/en",
          verified=CAPTURED, confidence="official"),
        O(code="", kind="referral", discount="Referral / promo codes supported at checkout",
          currency="", audience="all", where="web+app", scope="referral",
          expires="ongoing",
          terms=["'Remove promo code' control rendered in the checkout UI"],
          source="official", source_url="https://www.gomoworld.com/en",
          verified=CAPTURED, confidence="official"),
    ],
    "notes": ["GoMoWorld embeds per-country promo objects (e.g. US_30GB_30_+6GB) — real bonus-data offers, not codes.",
              "'GOMOWORLDFREE', 'GOMOWORLD50', 'WELCOME10' are flagged as expired/fake by the verifying publisher."],
}

# ---------------------------------------------------------------- Maya
BRANDS["maya"] = {
    "brand_key": "maya",
    "brand_name": "Maya Mobile",
    "brand_alias": ["maya.net"],
    "official_site": "https://maya.net/",
    "captured": CAPTURED,
    "offers": [
        O(code="ESIMTWEAKS10", kind="coupon", discount="10% off every plan", percent=10.0,
          currency="", audience="all", where="web+app", min_spend="none",
          scope="all plans incl. Cruise plans, 165+ countries",
          expires="ongoing",
          terms=["New and existing customers", "No minimum spend"],
          source="aggregator", source_url="https://esimtweaks.com/maya-mobile-coupon-code",
          verified="2026", confidence="verified-thirdparty"),
        O(code="AWESOME10", kind="coupon", discount="10% off all eSIM orders", percent=10.0,
          currency="", audience="all", where="web+app", scope="all eSIM orders",
          expires="ongoing",
          source="aggregator", source_url="https://goingawesomeplaces.com/best-esim-for-japan-travel/",
          verified="2026", confidence="reported"),
        O(code="FYESIM", kind="coupon", discount="10% off first Global Unlimited plan",
          percent=10.0, currency="", audience="new", where="web+app",
          scope="first Maya Global Unlimited plan purchase", expires="ongoing",
          terms=["Only valid on your first purchase"],
          source="aggregator", source_url="https://findyouresim.co.uk/discount-codes",
          verified="2026-09", confidence="reported"),
        O(code="MYBESTSIM", kind="coupon", discount="10% off (unlimited plans)", percent=10.0,
          currency="", audience="all", where="web+app", scope="unlimited data plans",
          expires="ongoing",
          source="aggregator", source_url="https://esim-korea.com/blog/esim-aktionscode",
          verified="2026", confidence="reported"),
        O(code="", kind="loyalty", discount="Maya Rewards — 6.6% back in points",
          percent=6.6, currency="", audience="existing", where="app",
          scope="points on every purchase", expires="ongoing",
          source="aggregator", source_url="https://esimtweaks.com/maya-mobile-coupon-code",
          verified="2026", confidence="reported"),
    ],
    "notes": ["Maya sells a single global-unlimited product; codes apply site-wide.",
              "maya.net HTML carries heavy embedded JSON but no coupon codes — codes are third-party."],
}

# ---------------------------------------------------------------- Yesim
BRANDS["yesim"] = {
    "brand_key": "yesim",
    "brand_name": "Yesim",
    "brand_alias": ["yesim.app"],
    "official_site": "https://yesim.app/",
    "captured": CAPTURED,
    "offers": [
        O(code="WELCOMETOYESIM", kind="coupon", discount="15% off first eSIM purchase",
          percent=15.0, currency="", audience="new", where="web+app",
          scope="first eSIM purchase", expires="ongoing",
          terms=["Published on Yesim's own Loyalty Program page"],
          source="official", source_url="https://yesim.app/loyalty-program/",
          verified=CAPTURED, confidence="official"),
        O(code="", kind="cashback", discount="5% cashback on every eSIM purchase",
          percent=5.0, currency="", audience="all", where="app",
          scope="credited to internal wallet (Ycoins)", expires="ongoing",
          source="official", source_url="https://yesim.app/loyalty-program/",
          verified=CAPTURED, confidence="official"),
        O(code="", kind="referral", discount="€5 for you + €5 for friend; every 5 friends +€50 (total €75)",
          amount=5.0, currency="EUR", audience="invited_friend", where="app",
          scope="referral — friend gets €5 on first top-up after you spend €5",
          expires="ongoing",
          terms=["Ladder: each friend €5, every 5 friends an extra €50 bonus (up to €75 total)"],
          source="official", source_url="https://yesim.app/referral-program/",
          verified=CAPTURED, confidence="official"),
        O(code="DREWDEAL", kind="coupon", discount="20% off Yesim eSIM plans", percent=20.0,
          currency="", audience="all", where="web+app", scope="all plans",
          expires="ongoing",
          terms=["Tested twice (incl. incognito) by the publisher, last verified 2026-09-10",
                 "Global Package 40GB/365d workthrough: A$117.30 -> A$93.84",
                 "Also credits ~4.69 AUD back in Ycoins after the plan ends"],
          source="aggregator", source_url="https://www.pointsbrotherhood.com/yesim-deal",
          verified="2026-09-10", confidence="verified-thirdparty"),
        O(code="MYBESTSIM20", kind="coupon", discount="20% off unlimited plans", percent=20.0,
          currency="", audience="all", where="web+app", scope="unlimited data plans",
          expires="ongoing",
          source="aggregator", source_url="https://esim-korea.com/blog/esim-aktionscode",
          verified="2026", confidence="reported"),
        O(code="LBO15", kind="coupon", discount="15% off first Yesim eSIM", percent=15.0,
          currency="", audience="new", where="web+app", scope="first eSIM",
          expires="ongoing",
          source="aggregator", source_url="https://lostbetweenoceans.com/?p=22133/",
          verified="2026", confidence="reported"),
        O(code="ESIMD", kind="coupon", discount="15% off", percent=15.0,
          currency="", audience="all", where="web+app", scope="eligible plans",
          expires="unknown", terms=["eSIM Deals partner code"],
          source="aggregator", source_url="https://www.esimdeals.io/esim/turkey/deals",
          verified="2026-09", confidence="verified-thirdparty"),
        O(code="Adapter", kind="coupon", discount="€3 off first purchase", amount=3.0,
          currency="EUR", audience="new", where="web+app", scope="first purchase",
          expires="ongoing",
          source="aggregator", source_url="https://toomanyadapters.com/?p=32246",
          verified="2026-08-31", confidence="reported"),
        O(code="", kind="student", discount="Student discounts", currency="",
          audience="students", where="web", scope="dedicated student-discounts page",
          expires="ongoing", source="official", source_url="https://yesim.app/",
          verified=CAPTURED, confidence="official"),
    ],
    "notes": ["Yesim's own loyalty page carries WELCOMETOYESIM (15% off first purchase) and the 5% cashback / €5+€5 referral ladder.",
              "Yesim nav lists 'Student discounts' and 'promo codes' pages (both 404 on direct fetch — content likely JS-gated)."],
}

# ---------------------------------------------------------------- Ubigi
BRANDS["ubigi"] = {
    "brand_key": "ubigi",
    "brand_name": "Ubigi",
    "brand_alias": ["ubigi.com"],
    "official_site": "https://www.ubigi.com/",
    "captured": CAPTURED,
    "offers": [
        O(code="PROMO15", kind="coupon", discount="15% off Unlimited plans", percent=15.0,
          currency="", audience="all", where="web+app",
          scope="unlimited-data plans (e.g. Vietnam, UAE unlimited)",
          expires="limited-time (countdown shown on plan pages)",
          terms=["Rendered as a promo top-bar with a copy button and countdown timer on Ubigi plan pages",
                 "This is Ubigi's own official on-site promo"],
          source="official",
          source_url="https://cellulardata.ubigi.com/rates-and-coverage/uae-data-plans/uae-10gb-30-days/",
          verified=CAPTURED, confidence="official"),
        O(code="WELCOME10", kind="coupon", discount="10% off all plans", percent=10.0,
          currency="", audience="new", where="web+app", scope="first eSIM data-plan purchase",
          expires="limited time",
          terms=["Not valid for monthly data plans"],
          source="aggregator", source_url="https://esimdiscounts.com/ubigi/promo-codes/",
          verified="2026-09-16", confidence="verified-thirdparty"),
        O(code="MYBESTSIM10", kind="coupon", discount="10% off all Ubigi eSIMs", percent=10.0,
          currency="", audience="all", where="web+app", scope="every plan and destination",
          expires="no known expiration (standing code)",
          terms=["Reusable on every new purchase", "Cannot combine with another deal"],
          source="aggregator", source_url="https://mybestsim.com/en/provider/ubigi-promo-code/",
          verified="2026-08-29", confidence="verified-thirdparty"),
        O(code="ESIMP", kind="coupon", discount="10% off first data plan", percent=10.0,
          currency="", audience="new", where="web+app", scope="first Ubigi data plan",
          expires="ongoing",
          source="aggregator", source_url="https://www.esimdeals.io/providers/ubigi",
          verified="2026", confidence="reported"),
        O(code="AWESOME10", kind="coupon", discount="10% off first order", percent=10.0,
          currency="", audience="new", where="web+app", scope="first order",
          expires="ongoing",
          source="aggregator", source_url="https://goingawesomeplaces.com/best-esims-for-usa-travel/",
          verified="2026", confidence="reported"),
        O(code="ESIMD", kind="coupon", discount="10% off", percent=10.0,
          currency="", audience="all", where="web+app", scope="eligible plans",
          expires="unknown", terms=["eSIM Deals partner code"],
          source="aggregator", source_url="https://www.esimdeals.io/esim/south-korea/deals",
          verified="2026-09", confidence="verified-thirdparty"),
    ],
    "notes": ["Ubigi's official on-site promo is PROMO15 (15% off Unlimited plans) — served via a promo top-bar injected into every plan page.",
              "ublock/Cloudflare blocks plain requests (403); rendered via Playwright."],
}

# ---------------------------------------------------------------- aloSIM
BRANDS["alosim"] = {
    "brand_key": "alosim",
    "brand_name": "aloSIM",
    "brand_alias": ["alosim.com"],
    "official_site": "https://alosim.com/",
    "captured": CAPTURED,
    "offers": [
        O(code="ESIMTWEAKS", kind="coupon", discount="15% off every plan", percent=15.0,
          currency="", audience="all", where="web+app", scope="country, regional, global, daily unlimited",
          expires="ongoing",
          terms=["New and returning customers", 
                 "Entered after picking a payment method",
                 "Won't combine with aloCASH wallet payments or vouchers"],
          source="aggregator", source_url="https://esimtweaks.com/alosim-promo-code",
          verified="2026", confidence="verified-thirdparty"),
        O(code="ESIMD", kind="coupon", discount="15% off first eSIM", percent=15.0,
          currency="", audience="new", where="web+app", scope="eligible plans",
          expires="ongoing",
          terms=["Latest proof 2026-09-18",
                 "Already-discounted or partner SKUs may be excluded"],
          source="aggregator", source_url="https://www.esimdeals.io/providers/alosim/deals",
          verified="2026-09-18", confidence="verified-thirdparty"),
        O(code="TRAVELESIMEXPERT", kind="coupon", discount="15% off all plans", percent=15.0,
          currency="", audience="all", where="web+app", scope="all plans",
          expires="ongoing",
          terms=["Anyone can use it", "Verified 2026-09-02 by the publisher"],
          source="aggregator", source_url="https://esimdiscounts.com/alosim/promo-codes/",
          verified="2026-09-02", confidence="verified-thirdparty"),
        O(code="FOOTLOOSEDEV", kind="coupon", discount="15% off", percent=15.0,
          currency="", audience="new", where="web+app", scope="eligible plans",
          expires="ongoing", terms=["New customers only (reported 2026-08-22)"],
          source="aggregator", source_url="https://esimdiscounts.com/alosim/promo-codes/",
          verified="2026-08-22", confidence="reported"),
        O(code="TRUECANADA", kind="coupon", discount="15% off", percent=15.0,
          currency="", audience="new", where="web+app", scope="eligible plans",
          expires="ongoing", terms=["New customers only (reported 2026-08-22)"],
          source="aggregator", source_url="https://esimdiscounts.com/alosim/promo-codes/",
          verified="2026-08-22", confidence="reported"),
        O(code="GOINGAWESOMEPLACES", kind="coupon", discount="15% off", percent=15.0,
          currency="", audience="all", where="web+app", scope="all plans",
          expires="ongoing",
          source="aggregator", source_url="https://goingawesomeplaces.com/best-esims-for-usa-travel/",
          verified="2026", confidence="reported"),
        O(code="TMA", kind="coupon", discount="$3 off first purchase", amount=3.0,
          currency="USD", audience="new", where="web+app", scope="first purchase",
          expires="ongoing",
          source="aggregator", source_url="https://toomanyadapters.com/?p=32246",
          verified="2026-08-31", confidence="reported"),
        O(code="", kind="referral", discount="Give $3 off, get $3 credit", amount=3.0,
          currency="USD", audience="invited_friend", where="app",
          scope="Refer & Earn — friend gets $3 off first purchase, you get $3 credit",
          expires="ongoing", source="official", source_url="https://alosim.com/",
          verified=CAPTURED, confidence="official"),
        O(code="", kind="loyalty", discount="Loyalty Program", currency="",
          audience="existing", where="app", scope="loyalty rewards",
          expires="ongoing", source="official", source_url="https://alosim.com/",
          verified=CAPTURED, confidence="official"),
        O(code="", kind="bonus_data", discount="Free international phone number + $3 calling credit (Hushed)",
          amount=3.0, currency="USD", audience="all", where="app",
          scope="bundled with every plan", expires="ongoing",
          source="official", source_url="https://alosim.com/",
          verified=CAPTURED, confidence="official"),
    ],
    "notes": ["aloSIM's standing codes cluster at 15% (ESIMTWEAKS / ESIMD / TRAVELESIMEXPERT).",
              "Official site is Cloudflare-403 to plain requests; rendered via Playwright.",
              "Homepage states a 15% off code 'TRAVELESIMEXPERT' on the Belgium page; the safest official figure is the Refer & Earn $3/$3."],
}

# ---------------------------------------------------------------- Firsty
BRANDS["firsty"] = {
    "brand_key": "firsty",
    "brand_name": "Firsty",
    "brand_alias": ["firsty.app"],
    "official_site": "https://www.firsty.app/",
    "captured": CAPTURED,
    "offers": [
        O(code="", kind="free_trial", discount="Free tier — ~20MB at 1Mbps, watch-ad unlock, 7-day validity",
          currency="", audience="new", where="app", scope="Firsty Free tier",
          expires="ongoing",
          source="official", source_url="https://www.firsty.app/",
          verified=CAPTURED, confidence="official"),
        O(code="", kind="referral", discount="Refer a Friend", currency="",
          audience="all", where="app", scope="referral programme",
          expires="ongoing", source="official", source_url="https://www.firsty.app/refer-a-friend",
          verified=CAPTURED, confidence="official"),
    ],
    "notes": ["Firsty sells one global price list (Free / Classic €0.98 per GB / Unlimited €2 per day); no per-country pricing.",
              "Its homepage JSON carries discount fields but all currently 0 — no standing % coupon found."],
}

# ---------------------------------------------------------------- Roamic
BRANDS["roamic"] = {
    "brand_key": "roamic",
    "brand_name": "Roamic",
    "brand_alias": ["roamic.com"],
    "official_site": "https://roamic.com/",
    "captured": CAPTURED,
    "offers": [
        O(code="TRAVELDEALZ10", kind="coupon", discount="10% off all packages", percent=10.0,
          currency="", audience="all", where="web+app", scope="all packages (single-country + regional + unlimited)",
          expires="valid until withdrawn",
          terms=["Entered at the final checkout step",
                 "e.g. 3GB/14d Thailand -> €2.70",
                 "North America unlimited from €4.99 per day"],
          source="aggregator", source_url="https://travel-dealz.com/coupon/roamic/",
          verified="2026-08-19", confidence="verified-thirdparty"),
        O(code="FYESIM10", kind="coupon", discount="10% off", percent=10.0,
          currency="", audience="all", where="web+app", scope="all plans",
          expires="ongoing",
          source="aggregator", source_url="https://findyouresim.co.uk/providers/roamic/vietnam/",
          verified="2026-09-17", confidence="verified-thirdparty"),
        O(code="Simpackers", kind="coupon", discount="10% off (new customers)", percent=10.0,
          currency="", audience="new", where="web+app", scope="new customers",
          expires="ongoing",
          source="aggregator", source_url="https://simpackers.com/deals/roamic-discount-code",
          verified="2026-09", confidence="reported"),
        O(code="ESIMP5", kind="coupon", discount="5% off", percent=5.0,
          currency="", audience="all", where="web+app", scope="eligible plans",
          expires="unknown", terms=["eSIM Deals partner code"],
          source="aggregator", source_url="https://www.esimdeals.io/providers/roamic",
          verified="2026-09-18", confidence="verified-thirdparty"),
        O(code="", kind="referral", discount="Referral 10% off", percent=10.0,
          currency="", audience="all", where="web+app", scope="referral code",
          expires="ongoing",
          source="aggregator", source_url="https://simpackers.com/deals/roamic-discount-code",
          verified="2026-09", confidence="reported"),
    ],
    "notes": ["Roamic is Spain-based, 190+ countries; no official coupons page found (all codes are third-party).",
              "Its own /promotions, /deals, /coupons, /referral paths all 404."],
}

# ---------------------------------------------------------------- Saily
BRANDS["saily"] = {
    "brand_key": "saily",
    "brand_name": "Saily",
    "brand_alias": ["saily.com"],
    "official_site": "https://saily.com/",
    "captured": CAPTURED,
    "offers": [
        O(code="ESIMD", kind="coupon", discount="10% off all plans", percent=10.0,
          currency="", audience="all", where="web+app", scope="all eSIMs incl. unlimited",
          expires="unknown",
          terms=["eSIM Deals partner code", "Discount visible as soon as the code validates"],
          source="aggregator", source_url="https://www.esimdeals.io/providers/saily/deals",
          verified="2026-09-22", confidence="verified-thirdparty"),
        O(code="ESIMDUDE", kind="coupon", discount="10% off eligible plans", percent=10.0,
          currency="", audience="all", where="web+app",
          scope="standard, regional, global and unlimited plans",
          expires="ongoing",
          terms=["New and existing users", "Applied in the 'Add promo code' field before payment"],
          source="aggregator", source_url="https://esimtweaks.com/saily-coupon-code",
          verified="2026-08-03", confidence="verified-thirdparty"),
        O(code="FYESIM", kind="coupon", discount="10% off", percent=10.0,
          currency="", audience="all", where="web+app", scope="all plans",
          expires="ongoing",
          source="aggregator", source_url="https://findyouresim.co.uk/providers/saily/uk-ireland/",
          verified="2026-09-17", confidence="reported"),
        O(code="GAP15", kind="coupon", discount="15% off all orders", percent=15.0,
          currency="", audience="all", where="web+app", scope="all orders",
          expires="ongoing",
          source="aggregator", source_url="https://goingawesomeplaces.com/best-esim-for-japan-travel/",
          verified="2026", confidence="reported"),
        O(code="ESIMADVICE", kind="coupon", discount="15% off", percent=15.0,
          currency="", audience="all", where="web+app", scope="eligible plans",
          expires="unknown",
          source="aggregator", source_url="https://esimtweaks.com/airalo-vs-saily",
          verified="2026", confidence="reported"),
        O(code="AFFMAVEN5", kind="coupon", discount="5% off (legacy fallback)", percent=5.0,
          currency="", audience="all", where="web+app", scope="all plan types",
          expires="ongoing", terms=["Legacy code — fallback if ESIMDUDE ever fails"],
          source="aggregator", source_url="https://esimtweaks.com/saily-coupon-code",
          verified="2026-08-03", confidence="reported"),
        O(code="vip15", kind="coupon", discount="15% off (whole site)", percent=15.0,
          currency="", audience="all", where="web+app", scope="all plans",
          expires="ongoing",
          source="aggregator", source_url="https://xincoupon.com/?p=44109/",
          verified="2026-10", confidence="reported"),
        O(code="", kind="referral", discount="Variable referral credit (new users only)",
          currency="", audience="new", where="app",
          scope="referral credit — can beat 10% on plans under ~$8",
          expires="ongoing",
          terms=["Not combinable with a code — one discount per order"],
          source="aggregator", source_url="https://esimtweaks.com/saily-coupon-code",
          verified="2026-08-03", confidence="reported"),
    ],
    "notes": ["Saily = Nord Security (NordVPN) brand, 150+ countries.",
              "'SAILY50', 'SAILY20' etc. tested by the publisher and do NOT work.",
              "Best verified standing code: ESIMD / ESIMDUDE (10%)."],
}

# ---------------------------------------------------------------- build

def to_row(brand, o):
    return {
        "brand": brand, "brand_name": BRANDS[brand]["brand_name"],
        "code": o["code"] or "", "kind": o["kind"], "discount": o["discount"] or "",
        "percent": "" if o["percent"] is None else o["percent"],
        "amount": "" if o["amount"] is None else o["amount"],
        "currency": o["currency"] or "", "audience": o["audience"] or "",
        "where": o["where"] or "", "min_spend": o["min_spend"] or "",
        "max_discount": o["max_discount"] or "", "stackable": o["stackable"] or "",
        "uses": o["uses"] or "", "scope": o["scope"] or "",
        "expires": o["expires"] or "", "source": o["source"] or "",
        "source_url": o["source_url"] or "", "verified": o["verified"] or "",
        "confidence": o["confidence"] or "",
        "terms": " | ".join(o["terms"]) if o["terms"] else "",
    }


def main():
    os.makedirs(OUT, exist_ok=True)
    rows = []
    for brand, data in BRANDS.items():
        offs = data["offers"]
        data["offer_count"] = len(offs)
        with open(os.path.join(OUT, brand + ".json"), "w", encoding="utf-8") as f:
            json.dump(data, f, ensure_ascii=False, indent=1)
        for o in offs:
            rows.append(to_row(brand, o))

    # combined json
    with open(os.path.join(OUT, "promos.json"), "w", encoding="utf-8") as f:
        json.dump({"captured": CAPTURED, "brand_count": len(BRANDS),
                   "offer_count": len(rows), "brands": BRANDS}, f,
                  ensure_ascii=False, indent=1)

    # csv
    cols = ["brand", "brand_name", "code", "kind", "discount", "percent", "amount",
            "currency", "audience", "where", "min_spend", "max_discount", "stackable",
            "uses", "scope", "expires", "source", "source_url", "verified",
            "confidence", "terms"]
    with open(os.path.join(OUT, "promos_all.csv"), "w", encoding="utf-8-sig", newline="") as f:
        w = csv.DictWriter(f, fieldnames=cols)
        w.writeheader()
        for r in rows:
            w.writerow(r)

    print("brands=%d  offers=%d" % (len(BRANDS), len(rows)))
    for b, d in BRANDS.items():
        kinds = {}
        for o in d["offers"]:
            kinds[o["kind"]] = kinds.get(o["kind"], 0) + 1
        print("  %-10s offers=%-3d %s" % (b, len(d["offers"]), kinds))


if __name__ == "__main__":
    main()
