# -*- coding: utf-8 -*-
"""Hardcoded-count guard: fail if hand-written content hardcodes site totals
that must stay data-derived (countries / providers / matchup pairs).

Rule (2026-10-02): counts come from data at build time.
  - layouts/*.html  → must use {{ len hugo.Data.* }}
  - content bodies  → must use {{< count-countries >}} / {{< count-providers >}} ...
  - front matter    → number-free wording (front matter can't run shortcodes)
  - EXEMPT: content/en/compare/<country>.md seo.description (regenerated by
    scripts/regen_meta_brand.py from live data — safe by regeneration)

Usage: python -X utf8 scripts/check_hardcoded.py
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PATTERNS = [
    re.compile(r"\b(?:50|fifty)\s+(?:countries|destinations)", re.I),
    re.compile(r"\b(?:8|eight)\s+providers", re.I),
    re.compile(r"\beight-plus\b", re.I),
    re.compile(r"\b28\s+(?:provider\s+)?matchups", re.I),
    re.compile(r"\bAll\s+28\b"),
]
COUNTRY_MD = re.compile(r"^content[\\/]en[\\/]compare[\\/]([a-z-]+)\.md$")

def strip_seo_desc(text: str) -> str:
    """Remove the regenerated seo.description value line from country pages."""
    return re.sub(r'(seo:\n  description: ")[^"]*(")', r"\1\2", text)

problems = []
checked = 0
for base in ("content/en", "layouts", "hugo.toml"):
    p = ROOT / base
    files = [p] if p.is_file() else sorted(x for x in p.rglob("*") if x.is_file())
    for f in files:
        rel = f.relative_to(ROOT).as_posix()
        if rel.startswith("content/en/compare/") and "-vs-" not in rel and not rel.endswith("_index.md") and "matchups" not in rel:
            text = strip_seo_desc(f.read_text(encoding="utf-8"))
        else:
            text = f.read_text(encoding="utf-8")
        checked += 1
        for pat in PATTERNS:
            for m in pat.finditer(text):
                line = text[:m.start()].count("\n") + 1
                problems.append(f"{rel}:{line}: \"{m.group(0)}\"")

print(f"files checked: {checked}")
if problems:
    print(f"HARDCODED TOTALS ({len(problems)}):")
    for p in problems:
        print("  !", p)
    print("\nFix: layouts → {{ len hugo.Data.* }} · content body → {{< count-countries >}} / "
          "{{< count-providers >}} / {{< count-app-providers >}} / {{< count-direct-providers >}} · "
          "front matter → number-free wording")
    sys.exit(1)
print("OK: no hardcoded totals")
