# -*- coding: utf-8 -*-
"""CSS sync guard: fail if any Tailwind class used in layouts/content is absent
from the compiled stylesheet (static/css/tailwind.css).

Why this exists (2026-10-03 incident):
  The site's CSS is built separately from Hugo:
      npm run build:css   ->  tailwindcss -i assets/css/main.css -o static/css/tailwind.css
  Running `hugo` alone does NOT recompile Tailwind. So editing a layout to use a
  new utility class (especially an arbitrary value such as
  `lg:grid-cols-[minmax(0,720px)_300px]`) silently produces a page whose class
  has no CSS rule behind it. Symptom seen in production: the right-hand sticky
  sidebar collapsed to the bottom of the page because the grid never got
  `grid-template-columns`.
  Tailwind's JIT never complains about unknown/typo'd classes either — it just
  omits them. This guard turns both failure modes into a hard build error.

Rule: layouts + content are the source of truth. Anything in a `class="..."`
attribute that is not a known non-Tailwind hook MUST exist in the compiled CSS.
Fix by running `npm run build:css`, or correct the class name.

Usage: python -X utf8 scripts/check_css_sync.py
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CSS_FILE = ROOT / "static" / "css" / "tailwind.css"

# Classes used only as JS/CSS hooks, never generated by Tailwind.
HOOKS = {
    "copy-code",   # copy button wiring in esim-deals/list.html
    "est-step",    # tool step widget in tools/list.html
}

# Attribute values containing any of these aren't static class lists.
TEMPLATE_MARKERS = ("{{", "}}", "{%")


def strip_comments(text: str) -> str:
    """Drop HTML and Hugo comments - they document markup, they don't emit any."""
    text = re.sub(r"<!--.*?-->", " ", text, flags=re.S)
    return re.sub(r"\{\{-?\s*/\*.*?\*/\s*-?\}\}", " ", text, flags=re.S)


def css_class_names(css: str) -> set:
    """All class names selectable from the compiled sheet.

    Handles Tailwind's escape format (`.lg\\:grid-cols-\\[minmax\\(0\\2c 720px\\)_300px\\]`)
    and attribute selectors (`.prose :where(p):not(:where([class~=not-prose], ...))`).
    """
    names = set()

    def unescape(sel: str) -> str:
        sel = sel.replace("\\2c ", ",").replace("\\2c", ",")
        return re.sub(r"\\(.)", r"\1", sel)

    for m in re.finditer(r"\.((?:\\2c |\\.|[^\s{},>+~():\[\]=])+)(?=[\s{},:>+~]|$)", css):
        c = unescape(m.group(1))
        if c:
            names.add(c)
    for m in re.finditer(r"\[class~=([^\]]+)\]", css):
        names.add(m.group(1))
    return names


def layout_classes() -> dict:
    """class token -> set of files declaring it (static attribute values only)."""
    found = {}
    targets = []
    for base in ("layouts", "content"):
        p = ROOT / base
        if p.is_dir():
            targets += [x for x in p.rglob("*") if x.suffix in (".html", ".md")]
    for f in sorted(targets):
        rel = f.relative_to(ROOT).as_posix()
        text = strip_comments(f.read_text(encoding="utf-8", errors="replace"))
        for m in re.finditer(r"""class\s*=\s*(["'])(.*?)\1""", text, re.S):
            value = m.group(2)
            if any(mk in value for mk in TEMPLATE_MARKERS):
                continue
            for tok in value.split():
                found.setdefault(tok, set()).add(rel)
    return found


def main() -> int:
    if not CSS_FILE.exists():
        print(f"ERROR {CSS_FILE.relative_to(ROOT).as_posix()} not found - run: npm run build:css")
        return 1

    known = css_class_names(CSS_FILE.read_text(encoding="utf-8"))
    declared = layout_classes()

    missing = {
        c: fs for c, fs in declared.items()
        if c not in known and c not in HOOKS
    }

    if missing:
        print("ERROR stale CSS: these classes are used in layouts/content but are")
        print("      absent from static/css/tailwind.css (run: npm run build:css)")
        for c in sorted(missing):
            print(f"  {c}")
            for f in sorted(missing[c])[:3]:
                print(f"      {f}")
        print(f"\n{len(missing)} unsynced class(es)")
        return 1

    print(f"OK: {len(declared)} layout classes all present in compiled CSS")
    return 0


if __name__ == "__main__":
    sys.exit(main())
